(function(root){"use strict";const A=root.ANITA51=root.ANITA51||{};
function say(l,en,ru,fi){return l==="ru"?ru:l==="fi"?(fi||en):en}function result(text,q,extra){return Object.assign({text,pending:q||null,sector:"secretary",showButtons:!!(q&&q.options&&q.options.length&&q.type!=="free")},extra||{})}
function missing(){const c=A.State.get().brief.confirmed,k=c.contact||{};if(!c.business)return"business";if(!c.goal)return"goal";if(!c.size)return"size";if(!Array.isArray(c.requirements)||!c.requirements.length)return"requirements";if(!k.firstName)return"firstName";if(!k.lastName)return"lastName";if(!k.phone)return"phone";if(!k.email)return"email";return null}
function summary(){const s=A.State.get(),c=s.brief.confirmed,l=s.language;return say(l,
"Great 😊 Here’s the brief I’ve built from what you told me:\n• ORDER NUMBER: "+s.brief.meta.orderNumber+"\n• Business / project: "+c.business+"\n• Website goal: "+c.goal+"\n• Size: "+c.size+"\n• Needs: "+c.requirements.join(", ")+"\n• Contact: "+c.contact.firstName+" "+c.contact.lastName+", "+c.contact.phone+", "+c.contact.email+"\n\nDoes everything look correct?",
"Отлично 😊 Вот бриф, который я составила из того, что вы рассказали:\n• НОМЕР ЗАКАЗА: "+s.brief.meta.orderNumber+"\n• Бизнес / проект: "+c.business+"\n• Цель сайта: "+c.goal+"\n• Размер: "+c.size+"\n• Нужно: "+c.requirements.join(", ")+"\n• Контакт: "+c.contact.firstName+" "+c.contact.lastName+", "+c.contact.phone+", "+c.contact.email+"\n\nВсё правильно?",
"Hienoa 😊 Tässä brief: \n• Yritys: "+c.business+"\n• Tavoite: "+c.goal+"\n• Koko: "+c.size+"\n• Tarpeet: "+c.requirements.join(", ")+"\n\nOnko kaikki oikein?")}
function next(){const id=missing();if(!id){const q=A.Questions.get("confirm");A.State.update({phase:"confirming"});A.State.setPending(q);return result(summary(),q)}const q=A.Questions.get(id);A.State.setPending(q);return result(A.Questions.prompt(q,A.State.get().language),q)}
function start(){A.State.resetBrief();return next()}
function sizeValue(v){const x=String(v).toLowerCase(),m=x.match(/\b(\d{1,2})\b/);if(m){const n=+m[1];return n===1?"one page":n===2?"two pages":n<=3?"a few pages":"four plus pages"}if(/one|одна|yksi|landing|лендинг/.test(x))return"one page";if(/two|две|два|kaksi/.test(x))return"two pages";if(/few|several|несколько|пару|muutama/.test(x))return"a few pages";if(/4\+|four plus|четыр|large|multi|больш|многостранич|laaja|monisivu/.test(x))return"four plus pages";return String(v).trim()}
function resolveGoal(v){const raw=String(v||"").trim(),x=raw.toLowerCase();const items=["browse work","buy online","contact the business","leave feedback","book a service"];
function joined(a){return a.join(", ")}
if(/all (of )?(that|those|them)|everything (you )?(listed|mentioned|said)|all you (listed|mentioned|said)|все( |,)?что (ты |вы )?(перечислил|перечислила|назвал|назвала)|всё перечисленное|kaikki (nuo|ne|mainitsemasi)/i.test(x))return joined(items);
if(/everything except|all except|все кроме|всё кроме|kaikki paitsi/.test(x)){let a=items.slice();if(/book|booking|запис|брон|varaa/.test(x))a=a.filter(z=>z!=="book a service");if(/feedback|review|отзыв|palaut/.test(x))a=a.filter(z=>z!=="leave feedback");if(/contact|связ|yhtey/.test(x))a=a.filter(z=>z!=="contact the business");if(/buy|purchase|куп|ost/.test(x))a=a.filter(z=>z!=="buy online");if(/browse|work|работ|töi/.test(x))a=a.filter(z=>z!=="browse work");return joined(a)}
const ord=x.match(/(?:first|перв|ensimmä)[^\d]*(?:two|2|два|две|kaksi)/);if(ord)return joined(items.slice(0,2));
let a=[];if(/browse|portfolio|work|работ|töi/.test(x))a.push(items[0]);if(/buy|purchase|shop|куп|покуп|ost/.test(x))a.push(items[1]);if(/contact|call|message|связ|контакт|yhtey/.test(x))a.push(items[2]);if(/feedback|review|отзыв|palaut/.test(x))a.push(items[3]);if(/book|booking|appointment|запис|брон|varaa/.test(x))a.push(items[4]);return a.length?joined(a):raw}
function normalizeRequirement(v){const raw=String(v||"").trim(),x=raw.toLowerCase();if(/customer|cusromer|cusromers|client|visitor/.test(x)&&/buy|purchase|order/.test(x))return "Customers should be able to buy products online";return raw}
function explainSize(){const l=A.State.get().language;return say(l,"One page is a single landing page. A few pages means separate pages such as About, Services and Contact. Larger multi-page is for a broader structure with many separate pages. Your size question is still open 😊","Одна страница — это лендинг. Несколько страниц — отдельные страницы вроде «О нас», «Услуги», «Контакты». Большой многостраничный — более широкая структура с множеством отдельных страниц. Вопрос о размере остаётся открытым 😊","Yksi sivu on landing page. Muutama sivu tarkoittaa erillisiä sivuja. Laaja monisivuinen sisältää useita erillisiä sivuja.")}
function answer(text){const s=A.State.get(),q=s.pending,v=String(text||"").trim(),x=v.toLowerCase();if(!q)return next();if(q.id==="inactivity"){if(v==="cancel"||/cancel|stop|отмен|не надо|peru/.test(x)){A.State.cancelBrief("user_cancelled");return result(say(s.language,"Of course 😊 I’ve cancelled the unfinished brief. Nothing will be sent to Alex.","Конечно 😊 Я отменила незавершённый бриф. Alex ничего не будет отправлено.","Selvä 😊 Peruin keskeneräisen briefin."),null,{cancelled:true})}const b=s.brief;b.meta=Object.assign({},b.meta,{status:"draft",lastActivityAt:Date.now(),inactivityPromptAt:null,expiresAt:null});A.State.update({brief:b,phase:"brief"});A.State.clearPending();return next()}
if(q.id==="size"&&(v==="clarify_size"||/difference|разниц|отлич|mitä eroa/.test(x)))return result(explainSize(),q);
if(q.id==="confirm"){if(/^(yes|да|верно|correct|ok|okay|kyllä|joo)/.test(x)){const b=Object.assign({},s.brief,{meta:Object.assign({},s.brief.meta,{confirmed:true,status:"confirmed",confirmedAt:Date.now(),lastActivityAt:Date.now(),inactivityPromptAt:null,expiresAt:null})}),h=A.Questions.get("handoff");A.State.update({brief:b,phase:"ready_handoff"});A.State.setPending(h);return result(say(s.language,"Perfect 😊 The brief is confirmed. Would you like me to pass it to Alex?","Отлично 😊 Бриф подтверждён. Передать его Alex?","Hienoa 😊 Brief on vahvistettu. Välitänkö sen Alexille?"),h)}
if(v==="prices"||/price|цен|hinn/.test(x))return result(A.Guide.prices(s.language)+"\n\n"+A.Questions.prompt(q,s.language),q);
if(v==="change"||/change|измен|muut/.test(x)){const e=A.Questions.get("edit");A.State.update({phase:"editing"});A.State.setPending(e);return result(A.Questions.prompt(e,s.language),e)}return result(A.Questions.prompt(q,s.language),q)}
if(q.id==="handoff"){if(v==="send"||/send|pass|перед|отправ|lähet/.test(x)){A.State.clearPending();A.State.update({phase:"handoff_requested"});return result("",null,{action:{type:"send_brief"}})}
if(v==="change"){const e=A.Questions.get("edit");A.State.update({phase:"editing"});A.State.setPending(e);return result(A.Questions.prompt(e,s.language),e)}
A.State.clearPending();A.State.update({phase:"confirmed"});return result(say(s.language,"No problem 😊 The brief stays confirmed. You can ask me to send it later.","Хорошо 😊 Бриф останется подтверждённым. Можете попросить отправить его позже.","Selvä 😊 Brief pysyy vahvistettuna."),null)}
if(q.id==="edit"){let target=null;if(/\b(size|pages?|page count|размер|страниц|koko|sivu)/i.test(x))target="size";else if(/\b(business|project|бизнес|проект|yritys)/i.test(x))target="business";else if(/\b(goal|purpose|цель|tavoite)/i.test(x))target="goal";else if(/\b(requirements?|needs?|пожелан|требован|tarpe)/i.test(x))target="requirements";if(target){const tq=A.Questions.get(target),b=Object.assign({},s.brief),cc=Object.assign({},b.confirmed);if(target==="requirements")cc.requirements=[];else cc[target]="";b.confirmed=cc;b.meta=Object.assign({},b.meta,{confirmed:false,sent:false});A.State.update({brief:b,phase:"brief",sector:"secretary",topic:"website"});A.State.setPending(tq);return result(say(s.language,target==="size"?"Of course. Roughly how large should the site be?":A.Questions.prompt(tq,"en"),target==="size"?"Конечно. Какого примерно размера нужен сайт?":A.Questions.prompt(tq,"ru"),A.Questions.prompt(tq,"fi")),tq)}return result(say(s.language,"Sure 😊 What would you like to change: the business, website goal, size, or requirements?","Конечно 😊 Что хотите изменить: бизнес, цель сайта, размер или пожелания?","Totta kai 😊 Mitä haluat muuttaa: yritystä, tavoitetta, kokoa vai tarpeita?"),q)}
const c=Object.assign({},s.brief.confirmed);if(q.id==="business")c.business=v;else if(q.id==="goal"){const map={contact:"contact the business",buy:"buy online",book:"book a service",learn:"learn about the business"};c.goal=map[v]||resolveGoal(v)}else if(q.id==="size")c.size=sizeValue(v);else if(q.id==="requirements"){if(v==="none"||/nothing|ничего|ei mitään/.test(x))c.requirements=["nothing special"];else c.requirements=[normalizeRequirement(v)]}else if(["firstName","lastName","phone","email"].includes(q.id)){c.contact=Object.assign({},c.contact||{});c.contact[q.id]=v}
A.State.update({brief:Object.assign({},s.brief,{confirmed:c}),sector:"secretary",topic:"website",phase:"brief"});A.State.clearPending();return next()}
function finishAmendments(){const s=A.State.get(),q=A.Questions.get("confirm");A.State.update({phase:"confirming"});A.State.setPending(q);return result(summary(),q,{amendmentsFinished:true})}
function amend(text){const s=A.State.get(),v=String(text||"").trim();if(!v)return null;const b=Object.assign({},s.brief),c=Object.assign({},b.confirmed),req=Array.isArray(c.requirements)?c.requirements.slice():[];if(!req.some(x=>String(x).toLowerCase()===v.toLowerCase()))req.push(v);c.requirements=req;b.confirmed=c;b.meta=Object.assign({},b.meta,{confirmed:false,sent:false});A.State.update({brief:b,sector:"secretary",topic:"website",phase:"brief_amended"});A.State.clearPending();return result(say(s.language,"Sure 😊 I’ve added this to your existing brief: "+v+". The brief is now updated and can be confirmed again whenever you’re ready.","Конечно 😊 Я добавила это в существующий бриф: "+v+". Бриф обновлён, и когда будете готовы, его можно подтвердить снова.","Totta kai 😊 Lisäsin tämän olemassa olevaan briefiin: "+v+"."),null,{amended:true})}
A.Secretary={start,answer,next,summary,amend,finishAmendments};})(window);