/* ANITA 51 — in-page multi-view demo site + autonomous Guide. No Secretary changes. */
(function(root){"use strict";const A=root.ANITA51=root.ANITA51||{},KEY="anita51_tour_v2";
const pages=[
{id:"home",title:"Home",lead:"Welcome to Alex Node",body:"Human-Tech websites, IT support and virtual characters designed around people.",guide:"Welcome. This is the home page — a quick introduction to Alex Node."},
{id:"about",title:"About",lead:"Technology with a personality.",body:"Alex Node develops practical digital services with a more human way of interacting with technology.",guide:"About explains Alex Node and the Human-Tech direction."},
{id:"services",title:"Services",lead:"Websites · IT · Virtual Characters",body:"Website creation, practical IT support, and character-based digital experiences.",guide:"Services shows the main areas Alex Node can help with."},
{id:"prices",title:"Prices",lead:"Clear starting points",body:"START 250 € · LIGHT 450 € · MEDIUM 620 € · CODE from 700 €.",guide:"Prices gives clear starting points for website packages."},
{id:"info",title:"Info",lead:"Ready for the next step?",body:"Explore the demo, talk with ANITA, or prepare a website brief.",guide:"Info is the last stop. From here you can keep exploring or talk with me."}
];
let timer=null,armed=false;
function read(){try{return JSON.parse(sessionStorage.getItem(KEY)||"null")}catch(_){return null}}function write(v){try{sessionStorage.setItem(KEY,JSON.stringify(v))}catch(_){}}function clear(){try{sessionStorage.removeItem(KEY)}catch(_){}if(timer)clearTimeout(timer);timer=null}
function site(){let el=document.getElementById("anita51-demo-site");if(el)return el;el=document.createElement("div");el.id="anita51-demo-site";el.innerHTML='<header><div class="an51-brand">ALEX NODE</div><nav></nav></header><main><div class="an51-kicker">ANITA 51 GUIDE TEST</div><h1></h1><h2></h2><p></p><div class="an51-panel"></div></main>';const rootEl=document.getElementById("an50-root");document.body.insertBefore(el,rootEl||document.body.firstChild);const nav=el.querySelector("nav");pages.forEach((p,i)=>{const b=document.createElement("button");b.type="button";b.textContent=p.title;b.onclick=()=>showPage(i,false);nav.appendChild(b)});return el}
function showPage(i,fromTour){const el=site(),p=pages[i];el.dataset.page=p.id;el.querySelector("h1").textContent=p.title;el.querySelector("h2").textContent=p.lead;el.querySelector("p").textContent=p.body;el.querySelector(".an51-panel").textContent="Separate demo view: "+p.title;[...el.querySelectorAll("nav button")].forEach((b,n)=>b.classList.toggle("active",n===i));history.replaceState(null,"","#"+p.id);if(fromTour)write({active:true,index:i});}
function bubble(){return document.getElementById("an50-bubble")}function choice(label,fn){const b=document.createElement("button");b.type="button";b.textContent=label;b.onclick=fn;return b}
function controls(text,buttons){const b=bubble();if(!b)return;b.innerHTML="";const d=document.createElement("div");d.textContent=text;b.appendChild(d);if(buttons&&buttons.length){const box=document.createElement("div");box.className="anita51-tour-controls";buttons.forEach(x=>box.appendChild(x));b.appendChild(box)}b.classList.add("show")}
function pose(name){if(root.ANITA50&&root.ANITA50.ui){root.ANITA50.ui.mode(name==="hello"?"intro":"guide-intro");root.ANITA50.ui.pose(name)}}
function image(){return document.getElementById("an50-img")} function rootBox(){return document.getElementById("an50-root")}
function armHello(){const box=rootBox(),img=image();if(!box||!img)return;armed=true;box.classList.add("anita51-guide-trigger");box.setAttribute("role","button");box.setAttribute("tabindex","0");box.setAttribute("aria-label","Open ANITA site guide");const fire=e=>{if(!armed)return;if(e){e.preventDefault();e.stopPropagation()}openInvitation()};box.onclick=fire;box.ontouchend=fire;box.onpointerup=fire;box.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){fire(e)}};box.oncontextmenu=e=>e.preventDefault();img.ondragstart=()=>false}
function disarmHello(){const box=rootBox();armed=false;if(!box)return;box.classList.remove("anita51-guide-trigger");box.removeAttribute("role");box.removeAttribute("tabindex");box.onclick=null;box.ontouchend=null;box.onpointerup=null;box.onkeydown=null}
function openInvitation(){if(!armed)return;disarmHello();pose("guide");controls("I’m ANITA — Alex Node IT Assistance 😊 I’m your guide around Alex Node. Tap me once more and I’ll show you around automatically.",[]);armGuide()}
function armGuide(){const box=rootBox();if(!box)return;armed=true;box.classList.add("anita51-guide-trigger");const fire=e=>{if(!armed)return;if(e){e.preventDefault();e.stopPropagation()}disarmHello();begin()};box.onclick=fire;box.ontouchend=fire;box.onpointerup=fire;box.oncontextmenu=e=>e.preventDefault()}
function readyToTalk(message){disarmHello();clear();if(root.ANITA50&&root.ANITA50.ui)root.ANITA50.ui.ready();const chat=document.getElementById("an50-chat");if(chat)chat.style.display="";controls(message||"I can help you plan a website, discuss design or IT, explain Alex Node services, or simply answer questions. For example, you can write: “I need a website”, “I need a logo”, or “Tell me about your services.” You can also just describe what you need in your own words.");const i=document.getElementById("an50-input");if(i)i.focus()}
function step(i){if(i>=pages.length){readyToTalk();return}showPage(i,true);pose("guide");controls(pages[i].guide,[choice("Stop tour",stop)]);timer=setTimeout(()=>{const s=read();if(s&&s.active)step(i+1)},i===0?5500:6500)}
function begin(){disarmHello();clear();write({active:true,index:0});step(0)}
function stop(){readyToTalk()}
function welcome(){clear();showPage(0,false);pose("hello");const b=bubble();if(b){b.innerHTML="";b.classList.remove("show")}armHello()}
function boot(){site();const hash=location.hash.replace("#",""),i=pages.findIndex(p=>p.id===hash);showPage(i>=0?i:0,false);setTimeout(welcome,250)}
A.SiteTour={boot,welcome,openInvitation,begin,stop,readyToTalk,pages,showPage};})(window);