/* Motor Engine Voice UI — Grok SPA session + Alex Node patch 1-3 */
(function(){
'use strict';
const SR=window.SpeechRecognition||window.webkitSpeechRecognition,A='assets/audio/';
const R={intro:'01_intro.mp3?v=9',services:'02_uslugi.mp3?v=9',prices:'03_ceny.mp3?v=9',contact:'04_kontakty.mp3?v=9',about:'05_o_nas.mp3?v=9',catalog:'06_varianty.mp3?v=9',detail:'07_podrobnosti.mp3?v=9',priceQuestion:'08_cena_chego.mp3?v=9',home:'09_glavnaya.mp3?v=9',booking:'10_zapis.mp3?v=9',diagnostics:'11_diagnostika.mp3?v=9',engine:'12_remont_dvigatelya.mp3?v=9',oil:'13_menyaem.mp3?v=9',tires:'14_shiny.mp3?v=9',hours:'15_chasy.mp3?v=9',address:'16_adres.mp3?v=9',phone:'17_telefon.mp3?v=9'};
const P={
'index.html':{title:'Motor Engine — Главная',nav:'index',html:'<div class="eyebrow">Smart Website · Voice User Interface</div><h1>ENGINEERING THAT MOVES YOU</h1><p class="lead">Motor Engine — демонстрационный многостраничный сайт с голосовым управлением. Скажите, что хотите найти, и сайт откроет нужную страницу.</p><div class="grid"><div class="card"><strong>Диагностика</strong><p>Компьютерная диагностика двигателя и электронных систем.</p></div><div class="card"><strong>Сервис</strong><p>Плановое обслуживание и ремонт автомобиля.</p></div><div class="card"><strong>Performance</strong><p>Настройка и решения для производительности.</p></div></div>'},
'services.html':{title:'Motor Engine — Услуги',nav:'services',html:'<div class="eyebrow">Услуги</div><h1>Сервис без лишних остановок</h1><p class="lead">Диагностика, техническое обслуживание и ремонт.</p><div class="grid"><div class="card"><strong>Диагностика двигателя</strong><p>Поиск ошибок и проверка ключевых систем.</p></div><div class="card"><strong>Техническое обслуживание</strong><p>Масла, фильтры, жидкости и плановые работы.</p></div><div class="card"><strong>Ремонт</strong><p>Механические и электрические работы.</p></div></div>'},
'prices.html':{title:'Motor Engine — Цены',nav:'prices',html:'<div class="eyebrow">Цены</div><h1>Понятные цены</h1><p class="lead">Демонстрационные цены Motor Engine.</p><div class="grid"><div class="card" id="price-49"><strong>Диагностика</strong><div class="price">49 €</div></div><div class="card" id="price-99"><strong>Service</strong><div class="price">99 €</div></div><div class="card" id="price-120"><strong>Repair</strong><div class="price">от 120 €</div></div></div>'},
'about.html':{title:'Motor Engine — О компании',nav:'about',html:'<div class="eyebrow">О компании</div><h1>Motor Engine</h1><p class="lead">Демонстрационный автосервис для тестирования Smart Website и Voice User Interface.</p><div class="grid"><div class="card"><strong>Точность</strong><p>Понятный процесс обслуживания.</p></div><div class="card"><strong>Технологии</strong><p>Современная диагностика и цифровой сервис.</p></div><div class="card"><strong>Клиент</strong><p>Информация находится быстро — в том числе голосом.</p></div></div>'},
'contact.html':{title:'Motor Engine — Контакты',nav:'contact',html:'<div class="eyebrow">Контакты</div><h1>Свяжитесь с Alex Node</h1><p class="lead">Есть вопрос по Smart Website или другим услугам? Свяжитесь удобным способом.</p><div class="grid" id="contact-options"><div class="card" id="contact-phone"><strong>Телефон</strong><p><a href="tel:+358458525293">+358 45 852 5293</a></p></div><div class="card" id="contact-email"><strong>Email</strong><p><a href="mailto:AN@alexnode.fi">AN@alexnode.fi</a></p></div><div class="card"><strong>WhatsApp</strong><p><a href="https://wa.me/358458525293" target="_blank">Написать в WhatsApp</a></p></div></div>'},
'catalog.html':{title:'Motor Engine — Варианты',nav:null,html:'<div class="eyebrow">Варианты</div><h1>Доступные варианты</h1><p class="lead">Эту отдельную страницу сайт открывает по голосовой команде.</p><div class="grid"><div class="card"><strong>Engine Care</strong><p>Диагностика и обслуживание.</p></div><div class="card"><strong>Season Check</strong><p>Сезонная проверка автомобиля.</p></div><div class="card"><strong>Performance</strong><p>Дополнительные решения и настройки.</p></div></div>'}
};
const D={
diagnostics:{title:'Motor Engine — Диагностика',html:'<div class="eyebrow">Подробнее · Диагностика</div><h1>Подробнее о диагностике</h1><p class="lead">Диагностика двигателя и электронных систем автомобиля.</p><div class="grid"><div class="card"><strong>Что проверяем</strong><p>ECU, датчики и параметры двигателя.</p></div><div class="card"><strong>Результат</strong><p>Понятное объяснение найденных проблем.</p></div><div class="card"><strong>Следующий шаг</strong><p>Ремонт или дополнительная проверка.</p></div></div>'},
service:{title:'Motor Engine — Service',html:'<div class="eyebrow">Подробнее · Service</div><h1>Подробнее о Service</h1><p class="lead">Плановое техническое обслуживание автомобиля.</p><div class="grid"><div class="card"><strong>Обслуживание</strong><p>Масла, фильтры, жидкости и плановые работы.</p></div><div class="card"><strong>Проверка</strong><p>Контроль основных систем и состояния автомобиля.</p></div><div class="card"><strong>Следующий шаг</strong><p>Рекомендации по дальнейшему обслуживанию.</p></div></div>'},
performance:{title:'Motor Engine — Performance',html:'<div class="eyebrow">Подробнее · Performance</div><h1>Подробнее о Performance</h1><p class="lead">Настройка и дополнительные решения для производительности автомобиля.</p><div class="grid"><div class="card"><strong>Настройка</strong><p>Подбор решений под автомобиль и задачи владельца.</p></div><div class="card"><strong>Performance</strong><p>Работы, связанные с производительностью и откликом автомобиля.</p></div><div class="card"><strong>Следующий шаг</strong><p>Обсуждение подходящего варианта и дальнейших работ.</p></div></div>'}
};
let active=false,r=null,speaking=false,audio=null,intro=false,current=(location.pathname.split('/').pop()||'index.html').split('?')[0];
const any=(t,x)=>x.some(v=>typeof v==='string'?t.includes(v):v.test(t));
function status(txt,color){const e=document.querySelector('.status');if(e){e.textContent=txt;if(color)e.style.color=color}}
function compact(){const v=document.querySelector('.voice');if(!v)return;v.style.cssText+=';width:auto;max-width:none;padding:8px 12px;left:auto;right:12px;bottom:12px;border-radius:999px';const h=v.querySelector('.hints'),x=v.querySelector('.heard'),b=v.querySelector('.mic');if(h)h.style.display='none';if(x)x.style.display='none';if(b)b.style.display='none';status('●','#35d06f')}
function listen(){if(!r||!active||speaking)return;try{r.start()}catch(e){}}
function play(k){const f=R[k];if(!f)return Promise.resolve();try{sessionStorage.setItem('motorLastReply',k)}catch(e){};speaking=true;if(r)try{r.abort()}catch(e){};if(audio)try{audio.pause()}catch(e){};audio=new Audio(A+f);return new Promise((ok,no)=>{audio.onended=()=>{speaking=false;audio=null;if(active)setTimeout(listen,280);ok()};audio.onerror=e=>{speaking=false;audio=null;if(active)setTimeout(listen,280);no(e)};audio.play().catch(e=>{speaking=false;if(active)setTimeout(listen,280);no(e)})})}
function highlight(id){const e=document.getElementById(id);if(!e)return;document.querySelectorAll('.voice-target-highlight').forEach(x=>x.classList.remove('voice-target-highlight'));e.classList.add('voice-target-highlight');e.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>e.classList.remove('voice-target-highlight'),5200)}
function navActive(n){document.querySelectorAll('.nav a').forEach(a=>{a.classList.remove('active');if(n&&(a.getAttribute('href')||'')===n+'.html')a.classList.add('active')})}
function go(page,reply,target,push=true){const d=P[page],m=document.querySelector('main.content');if(!d||!m)return;m.innerHTML=d.html;document.title=d.title;navActive(d.nav);current=page;if(push)history.pushState({page},d.title,page);if(reply)setTimeout(()=>play(reply).finally(()=>target&&highlight(target)),60);else if(target)setTimeout(()=>highlight(target),100)}
function detail(k,reply){const d=D[k],m=document.querySelector('main.content');if(!d||!m)return;m.innerHTML=d.html;document.title=d.title;navActive(null);current='service-detail.html';history.pushState({page:'service-detail.html',service:k},d.title,'service-detail.html?service='+k);if(reply)setTimeout(()=>play(reply).catch(()=>{}),60)}
function price(t){if(!/(€|\bевро\b|\beuro\b|\beuros\b)/i.test(t))return null;if(/\b49\b/.test(t)||t.includes('сорок девять'))return'price-49';if(/\b99\b/.test(t)||t.includes('девяносто девять'))return'price-99';if(/\b120\b/.test(t)||t.includes('сто двадцать'))return'price-120';return null}
function handle(raw){let t=raw.toLowerCase().replace(/ё/g,'е').replace(/[?!.,]/g,' ').replace(/\s+/g,' ').trim(),p=price(t);if(p)return current==='prices.html'&&document.getElementById(p)?highlight(p):go('prices.html','',p);
if(any(t,[/^что$/, /^чего$/,'повтори','повторите','еще раз','не расслышал'])){let k=sessionStorage.getItem('motorLastReply');if(k)return play(k)}
if(any(t,[/(позвон|звон).*(ватсап|вацап|вотсап|whatsapp)/]))return location.href='https://wa.me/358458525293';
if(any(t,['позвони','позвонить','набери номер']))return location.href='tel:+358458525293';
if(any(t,[/^performance$/, /^перформанс$/,'performance','перформанс']))return detail('performance','detail');
if(any(t,[/^service$/, /^сервис$/,'техническое обслуживание','подробнее про service','подробнее про сервис']))return detail('service','detail');
if(any(t,['диагностика','диагностировать','проверить машину','проверить автомобиль']))return detail('diagnostics','diagnostics');
if(any(t,['цены','прайс','тарифы','покажи цены']))return go('prices.html','prices');
if(any(t,['услуги','покажи услуги','что вы делаете','чем занимаетесь']))return go('services.html','services');
if(any(t,['контакты','покажи контакты','как связаться']))return go('contact.html','contact','contact-options');
if(any(t,['о компании','о вас','кто вы']))return go('about.html','about');
if(any(t,['каталог','варианты','покажи варианты']))return go('catalog.html','catalog');
if(any(t,['главная','на главную','домой']))return go('index.html','home');
if(any(t,['телефон','номер телефона','покажи номер']))return go('contact.html','phone','contact-phone');
if(any(t,['email','e mail','имейл','емейл']))return go('contact.html','contact','contact-email');
}
function overlay(){if(document.getElementById('voice-start'))return;const o=document.createElement('div');o.id='voice-start';o.style.cssText='position:fixed;inset:0;z-index:99999;background:rgba(5,7,12,.82);display:flex;align-items:center;justify-content:center;padding:24px';o.innerHTML='<div style="max-width:440px;background:#11151d;border:1px solid #ff7a00;border-radius:20px;padding:28px;text-align:center;color:#fff"><div style="font-size:42px">🎙</div><h2>Используйте навигацию голосом</h2><p style="color:#c7cbd1">Нажмите микрофон один раз, чтобы управлять сайтом голосом. После этого можно просто говорить команды.</p><button id="voice-start-btn" style="border:0;border-radius:999px;padding:14px 22px;font-weight:700;cursor:pointer">🎙 Включить микрофон</button></div>';document.body.appendChild(o);o.querySelector('button').onclick=()=>{active=true;localStorage.setItem('motorVoiceSession','1');o.remove();compact();if(!intro){intro=true;play('intro').catch(()=>{})}}}
function init(){if(SR){r=new SR();r.lang='ru-RU';r.interimResults=false;r.continuous=false;r.onstart=()=>status('●','#35d06f');r.onend=()=>{if(active&&!speaking)setTimeout(listen,280)};r.onerror=e=>{if(e.error==='not-allowed'||e.error==='service-not-allowed'){active=false;status('●','#e5484d')}else if(active&&!speaking)setTimeout(listen,300)};r.onresult=e=>setTimeout(()=>handle(e.results[0][0].transcript),60)}
document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;const h=a.getAttribute('href')||'',k=h.split('/').pop().split('?')[0];if(P[k]&&!h.startsWith('http')){e.preventDefault();go(k,'',null,true)}},true);
addEventListener('popstate',e=>{const k=e.state&&e.state.page;if(P[k])go(k,'',null,false)});
if(localStorage.getItem('motorVoiceSession')==='1'){active=true;intro=true;compact();setTimeout(listen,400)}else overlay()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();