/* ANITA Engine Experiment — Interpreter (Human-Tech) */
(function(root){"use strict";const W=(root.ANITA50=root.ANITA50||{});
function say(lang,en,ru,fi){if(lang==='ru')return ru;if(lang==='fi')return fi||en;return en;}
function detectRole(text,state){const x=(text||'').toLowerCase();if(/\b(windows|wifi|wi-fi|printer|драйвер|driver|компьютер|computer|ноутбук|ошибка|error|синий экран|bsod|не работает|роутер|router|антивирус|тормозит|зависает|принтер)\b/i.test(x))return'it_assistant';if(/\b(хочу сайт|нужен сайт|сделать сайт|заказать сайт|website|verkkosivu|landing|лендинг|мой бизнес|автомастерск)\b/i.test(x))return'business_consultant';if(/\b(guide me|покажи сайт|проведи|где цены|portfolio|услуги|services|контакты|where are)\b/i.test(x))return'guide';return state.role||'guide';}
function isGreeting(t){return/^(hi|hello|hey|привет|здравствуй|здравствуйте|добрый день|hei|moi|moikka)([!.]?)$/i.test(String(t||'').trim());}
function isSmallTalk(t){return/\b(как дела|how are you|что делаешь|спасибо|thank you|thanks|круто|cool)\b/i.test(String(t||'').toLowerCase());}
function isIdentityQuestion(t){return/\b(ты (ии|ai|бот|робот|человек)|are you (ai|a bot|human|real)|how do you work|как ты работаешь|что ты такое|who are you|ты кто)\b/i.test(String(t||'').toLowerCase());}
function isHandoffRequest(t){const x=String(t||'').toLowerCase();const pass=/(pass|send|forward|give|передай|отправь|отправить|передать|lähetä|välitä)/i.test(x),brief=/(brief|бриф|project|проект)/i.test(x),alex=/(alex|алекс)/i.test(x);return (pass&&brief)||(pass&&alex)||(brief&&alex&&/(ready|готов|continue|продолж)/i.test(x));}
function handoffReply(lang,brief){const c=(brief&&brief.confirmed)||{};const parts=[];if(c.business)parts.push((lang==='ru'?'Бизнес / проект: ':'Business / project: ')+c.business);if(c.goal)parts.push((lang==='ru'?'Цель сайта: ':'Website goal: ')+c.goal);if(c.size)parts.push((lang==='ru'?'Размер: ':'Size: ')+c.size);if(c.requirements&&c.requirements.length)parts.push((lang==='ru'?'Пожелания: ':'Needs: ')+c.requirements.join(', '));const body=parts.join('\n');return say(lang,'Your brief is ready for Alex 😊\n\n'+body+'\n\nThis test version does not yet have a real send-to-Alex connection, so I have not claimed that it was sent. The next step is to connect the handoff action to email/backend.','Бриф для Alex готов 😊\n\n'+body+'\n\nВ этой тестовой версии реальная отправка Alex ещё не подключена, поэтому я не буду говорить, что уже отправила его. Следующий шаг — подключить handoff к email/backend.','Briefi Alexille on valmis 😊\n\n'+body+'\n\nTässä testiversiossa oikeaa lähetysyhteyttä Alexille ei ole vielä kytketty.');}
const Interpreter={async handle(userText){const DS=W.engine.DialogueState,Pending=W.engine.Pending,TG=W.engine.TurnGuard,Brief=W.engine.BriefFlow,Extract=W.engine.Extract;if(!DS||!Pending||!TG)return{error:'engine_not_ready',replies:[]};const turnId=TG.beginTurn();let state=DS.get(),language=state.language||Pending.detectLanguage(userText);if(!state.language){DS.setLanguage(language);state=DS.get();}const text=String(userText||'').trim();if(!text)return{turnId,language,role:state.role,replies:[],actions:[]};DS.update({lastUser:text});state=DS.get();
if(isIdentityQuestion(text)&&W.engine.Human)return{turnId,language,role:state.role||'guide',replies:[{text:W.engine.Human.identityReply(language),pose:'neutral'}],usedAI:false};
/* Critical state transition: a confirmed brief must not re-enter BriefFlow. */
if(state.conversationState==='ready_handoff'&&isHandoffRequest(text)){DS.update({conversationState:'handoff_ready',role:'business_consultant',topic:'website_order',pendingQuestion:null});return{turnId,language,role:'business_consultant',replies:[{text:handoffReply(language,DS.get().websiteBrief),pose:'success'}],handoff:{status:'ready',brief:DS.get().websiteBrief},showButtons:false,usedAI:false};}
if(state.conversationState==='ready_handoff'){return{turnId,language,role:'business_consultant',replies:[{text:say(language,'The brief is already confirmed 😊 If you want, say “pass the brief to Alex”. You can also ask me something about the project first.','Бриф уже подтверждён 😊 Если хотите, скажите «передай бриф Alex». Или можете сначала спросить что-нибудь о проекте.','Briefi on jo vahvistettu 😊 Voit pyytää minua välittämään sen Alexille.'),pose:'neutral'}],usedAI:false};}
if(state.pendingQuestion){const interp=Pending.interpret(state.pendingQuestion,text,language);if(interp.kind==='clarification')return{turnId,language,role:state.role,replies:[{text:interp.text,pose:'neutral'}],pendingQuestion:state.pendingQuestion,showButtons:!!(state.pendingQuestion.options&&state.pendingQuestion.options.length),usedAI:false};if(interp.kind==='side_question'&&state.pendingQuestion.id==='confirm_brief'){let sideText=Brief&&Brief.answerConfirmSideQuestion?Brief.answerConfirmSideQuestion(text,language):null;if(sideText)return{turnId,language,role:'business_consultant',replies:[{text:sideText,pose:'professional'}],pendingQuestion:state.pendingQuestion,showButtons:true,usedAI:false};}if(interp.kind==='unsure')return{turnId,language,role:state.role,replies:[{text:say(language,'No worries 😊 '+Pending.promptOf(state.pendingQuestion,language),'Ничего 😊 '+Pending.promptOf(state.pendingQuestion,language),'Ei se mitään 😊 '+Pending.promptOf(state.pendingQuestion,language)),pose:'neutral'}],pendingQuestion:state.pendingQuestion,showButtons:true,usedAI:false};if(interp.kind==='answer'&&Brief){const next=Brief.applyAnswer(state.pendingQuestion,interp.value,language,turnId);if(next&&TG.isActive(turnId))return Object.assign({turnId,language,usedAI:false},next);}if(state.conversationState==='brief'||state.topic==='website_order'){if(Brief&&Extract){const facts=Extract.extractFacts(text),rich=facts.business||facts.size||facts.requirements.length||facts.goal;if(rich){const next=await Brief.absorb(text,language,turnId);if(next&&TG.isActive(turnId))return Object.assign({turnId,language,usedAI:false},next);}}}if(interp.kind==='unknown')return{turnId,language,role:state.role,replies:[{text:say(language,'Just to be sure — '+Pending.promptOf(state.pendingQuestion,language),'Уточню 😊 '+Pending.promptOf(state.pendingQuestion,language),'Varmistan 😊 '+Pending.promptOf(state.pendingQuestion,language)),pose:'neutral'}],pendingQuestion:state.pendingQuestion,showButtons:!!(state.pendingQuestion.options&&state.pendingQuestion.options.length),usedAI:false};}
if(isGreeting(text)||isSmallTalk(text)){DS.setRole('guide');let reply=isGreeting(text)?say(language,"Hi 😊 I'm ANITA — Alex Node IT Assistance. How can I help?","Привет 😊 Я ANITA — Alex Node IT Assistance. Чем могу помочь?","Hei 😊 Olen ANITA — Alex Node IT Assistance. Kuinka voin auttaa?"):say(language,"I'm here 😊 What would you like to do?","Я здесь 😊 Что хотите сделать?","Olen täällä 😊 Mitä haluaisit tehdä?");const flags=DS.get().flags||{};if(!flags.askedGoal){const q=Pending.get('goal');DS.update({flags:{askedGoal:true,greeted:true},pendingQuestion:q,conversationState:'asking_goal',role:'guide'});return{turnId,language,role:'guide',replies:[{text:reply,pose:'neutral'},{text:Pending.promptOf(q,language),pose:'ready'}],pendingQuestion:q,usedAI:false};}return{turnId,language,role:'guide',replies:[{text:reply,pose:'neutral'}],usedAI:false};}
const role=detectRole(text,state);DS.setRole(role);if(role==='business_consultant'&&Brief&&Extract){const next=await Brief.absorb(text,language,turnId);if(next&&TG.isActive(turnId))return Object.assign({turnId,language,usedAI:false},next);}if(role==='guide'&&/\b(цен|price|pricing|hinnat)\b/i.test(text))return{turnId,language,role,replies:[{text:say(language,'Website packages: START 250 €, LIGHT 450 €, MEDIUM 620 €, CODE from 700 €.','Пакеты на сайты: START 250 €, LIGHT 450 €, MEDIUM 620 €, CODE от 700 €.','Verkkosivupaketit: START 250 €, LIGHT 450 €, MEDIUM 620 €, CODE alkaen 700 €.'),pose:'professional'}],usedAI:false};if(!DS.get().flags.askedGoal){const q=Pending.get('goal');DS.update({flags:{askedGoal:true},pendingQuestion:q,conversationState:'asking_goal',role:'guide'});if(/\b(сайт|website|sivusto|лендинг)\b/i.test(text)&&Brief){const next=await Brief.absorb(text,language,turnId);if(next)return Object.assign({turnId,language,usedAI:false},next);}return{turnId,language,role:'guide',replies:[{text:Pending.promptOf(q,language),pose:'ready'}],pendingQuestion:q,usedAI:false};}if(W.engine.AI&&typeof W.engine.AI.ask==='function'){const guarded=TG.guard(turnId,()=>W.engine.AI.ask(text,language,{role:DS.get().role,topic:DS.get().topic,brief:DS.get().websiteBrief})),ai=await guarded();if(ai===TG.STALE)return{turnId,language,role:DS.get().role,replies:[],stale:true,usedAI:true};if(ai&&ai.ok&&ai.answer)return{turnId,language,role:DS.get().role,replies:[{text:ai.answer,pose:'neutral'}],usedAI:true};}return{turnId,language,role:DS.get().role,replies:[{text:say(language,"I'm with you 😊 Website, IT help, or a walk around the site — what do you need?","Я на связи 😊 Сайт, IT-помощь или пройтись по сайту — что нужно?","Olen mukana 😊 Verkkosivu, IT-apu vai kierros sivustolla — mitä tarvitset?"),pose:'neutral'}],usedAI:false};}};
W.engine=W.engine||{};W.engine.Interpreter=Interpreter;console.log('[ANITA Engine] interpreter ready (Human-Tech + handoff)');})(typeof window!=='undefined'?window:globalThis);
