/* ANITA Engine Experiment — robust test UI binding */
(function(root){
"use strict";
const W=(root.ANITA50=root.ANITA50||{});
function bubble(){return document.getElementById("an50-bubble")||document.getElementById("anita-live-bubble")||document.querySelector("[data-anita-bubble]");}
function write(text){const el=bubble();if(!el)return;el.textContent=String(text||"");el.classList.add("show");}
function ensureStyle(){if(document.getElementById("anita-engine-btn-style"))return;const s=document.createElement("style");s.id="anita-engine-btn-style";s.textContent='.anita-engine-choices{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px;max-width:100%}.anita-engine-choices button{padding:8px 12px;border-radius:18px;border:1px solid #c9c9c9;background:#fff;cursor:pointer;font-size:13px;line-height:1.2}.anita-engine-choices button.primary{background:#2d6a4f;color:#fff;border-color:#2d6a4f}';document.head.appendChild(s);}
function renderButtons(pending,language){ensureStyle();const host=bubble();if(!host||!pending||!pending.options||!pending.options.length)return;let box=host.querySelector('.anita-engine-choices');if(box)box.remove();box=document.createElement('div');box.className='anita-engine-choices';pending.options.forEach(opt=>{const bt=document.createElement('button');bt.type='button';bt.textContent=(opt.labels&&(opt.labels[language]||opt.labels.en))||opt.value;if(opt.value==='yes')bt.classList.add('primary');bt.onclick=()=>{const input=document.getElementById('an50-input')||document.getElementById('anita-mini-input'),send=document.getElementById('an50-send')||document.getElementById('anita-mini-send');if(input&&send){input.value=opt.value==='yes'?(language==='ru'?'Да':'Yes'):opt.value==='no'?(language==='ru'?'Нет':'No'):(opt.labels&&opt.labels[language])||opt.value;send.click();}};box.appendChild(bt);});host.appendChild(box);}
function showReplies(result){if(!result)return;if(result.error){write('TEST ENGINE ERROR: '+result.error);return;}const replies=Array.isArray(result.replies)?result.replies:[];const texts=replies.map(r=>r&&r.text).filter(Boolean);if(!texts.length){write('TEST ENGINE: message received, but engine returned no reply.');return;}write(texts.join('\n\n'));if(result.showButtons&&result.pendingQuestion)setTimeout(()=>renderButtons(result.pendingQuestion,result.language||'en'),20);}
function showError(err){console.error('[ANITA Grok runtime]',err);write('TEST ENGINE ERROR: '+String(err&&err.message||err));}
async function onUserSend(text){write('ANITA is thinking…');try{const Interpreter=W.engine&&W.engine.Interpreter;if(!Interpreter||typeof Interpreter.handle!=='function')throw new Error('Interpreter is not loaded');const result=await Interpreter.handle(text);if(result&&result.stale){write('TEST ENGINE ERROR: reply was marked stale (turnId '+String(result.turnId)+').');return result;}showReplies(result);return result;}catch(err){showError(err);return null;}}
function bind(){const input=document.getElementById('an50-input')||document.getElementById('anita-mini-input'),send=document.getElementById('an50-send')||document.getElementById('anita-mini-send');if(!input||!send){write('TEST ENGINE ERROR: input/send elements not found');return;}if(send.dataset.engineBound==='robust1')return;send.dataset.engineBound='robust1';const run=async e=>{if(e){e.preventDefault();e.stopImmediatePropagation();}const text=input.value.trim();if(!text)return;input.value='';await onUserSend(text);};send.addEventListener('click',run,true);input.addEventListener('keydown',e=>{if(e.key==='Enter')run(e);},true);console.log('[ANITA Engine] robust UI bound');}
function boot(){bind();setTimeout(bind,250);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
W.engine=W.engine||{};W.engine.UIBind={showReplies,renderButtons,bind,onUserSend,write};
})(typeof window!=='undefined'?window:globalThis);
