/* ANITA 0.3.0 — HUMAN-TECH CORE
 * One dispatcher owns the conversation. Roles/semantic modules are tools only;
 * they never receive a visitor message until the router has decided why.
 */
(function(){
"use strict";
const C=window.ANITA50_CONFIG,W=window.ANITA50=window.ANITA50||{},R=W.router030;
if(!C||!W.state||!W.ui||!W.roles||!W.ai||!R||W.__core030)return;
W.__core030=true;

const q=()=>document.getElementById("an50-input"),s=()=>document.getElementById("an50-send");
const clean=x=>String(x==null?"":x).trim();
const say=(l,en,ru,fi)=>l==="ru"?(ru||en):l==="fi"?(fi||en):en;
const uniq=a=>[...new Set((a||[]).map(v=>clean(v).toLowerCase()).filter(Boolean))];
const home=()=>((location.pathname||"/").replace(/\/+$/,"")||"/")==="/";
let busy=false,queue=[];

function freshBrief(){return{business:null,businessDescription:null,goal:null,size:null,requirements:[],inferredSuggestions:[],rejectedSuggestions:[],customerSignals:[],recommendedPackage:null,recommendedStructure:null,needsAlexReview:false};}
function withBrief(b){return Object.assign(freshBrief(),b||{}, {requirements:uniq((b&&b.requirements)||[]),inferredSuggestions:uniq((b&&b.inferredSuggestions)||[]),rejectedSuggestions:uniq((b&&b.rejectedSuggestions)||[]),customerSignals:uniq((b&&b.customerSignals)||[])});}
function hasProject(c){const b=withBrief(c&&c.websiteBrief);return !!(b.business||b.goal||b.size||b.requirements.length);}
function nextPending(c){const b=withBrief(c&&c.websiteBrief);if(!b.business)return"business";if(!b.goal)return"goal";if(!b.size)return"size";return null;}
function splitBusiness(raw){const x=clean(raw).replace(/[.!?,;:]+$/g,"").trim();if(!x)return{business:null,description:null};const ps=[/^(.{2,55}?)\s+(?:,?\s*(?:and\s+)?)?(i|we)\s+(sell|repair|provide|offer|make|build|serve|stock|supply|install|design|create|help)\s+(.+)$/i,/^(.{2,55}?)\s+(?:where|that)\s+(i|we)\s+(sell|repair|provide|offer|make|build|serve|stock|supply|install|design|create|help)\s+(.+)$/i];for(const rx of ps){const m=x.match(rx);if(m){const business=clean(m[1]).replace(/[,-]+$/g,"").trim();if(business.length>=2)return{business,description:(m[2]+" "+m[3]+" "+m[4]).trim()};}}return{business:x,description:null};}
function sectionCount(v){const m=clean(v).match(/^(\d{1,2})\s+(?:sections?\s*\/\s*pages?|sections?|pages?)$/i);return m?Number(m[1]):null;}
function badGoal(x){return R.greeting(x)||R.smalltalk(x)||R.meta(x);}
function sanitizeBrief(input){const b=withBrief(input),req=[];let count=null;for(const v of b.requirements){const n=sectionCount(v);if(n!=null){count=count||n;continue;}req.push(v);}b.requirements=uniq(req);if(count&&!b.size)b.size=count===1?"one landing page":count<=5?"a few separate pages":"a larger multi-page site";if(b.business){const p=splitBusiness(b.business);b.business=p.business;if(p.description&&!b.businessDescription)b.businessDescription=p.description;}if(b.goal&&badGoal(b.goal))b.goal=null;return b;}
function sanitizeMemory(m,b){const out=Object.assign({name:null,business:null,businessRaw:null,businessDescription:null,contact:{name:null,email:null,phone:null}},m||{});out.contact=Object.assign({name:null,email:null,phone:null},out.contact||{});if(out.business){const p=splitBusiness(out.business);out.business=p.business;if(p.description&&!out.businessDescription)out.businessDescription=p.description;}if(b&&b.business)out.business=b.business;if(b&&b.businessDescription)out.businessDescription=b.businessDescription;return out;}
function sanitizeStored(){const c=W.state.context(),b=sanitizeBrief(c.websiteBrief),m=sanitizeMemory(c.clientMemory,b);const patch={websiteBrief:b,clientMemory:m};if(c.topic==="website_consultation"&&!c.pendingAction&&!c.pending&&(!b.goal||!b.business||!b.size))patch.pending=nextPending({websiteBrief:b});W.state.patch(patch);}

function projectLabel(c,l){const b=sanitizeBrief(c.websiteBrief),m=sanitizeMemory(c.clientMemory,b),name=b.business||m.business;return name||say(l,"your website project","ваш проект сайта","verkkosivuprojektisi");}
function pendingQuestion(c,l){const pa=String(c.pendingAction||"");if(pa.startsWith("confirm_need:")&&W.semanticAdapter&&W.semanticAdapter.questionForNeed)return W.semanticAdapter.questionForNeed(pa.slice("confirm_need:".length),l,c.websiteBrief||{});if(c.pending==="business")return say(l,"What kind of business is the website for?","Для какого бизнеса нужен сайт?","Millaiselle yritykselle sivusto tulee?");if(c.pending==="goal")return say(l,"What should visitors mainly be able to do on the website?","Что посетители должны в первую очередь уметь делать на сайте?","Mitä kävijöiden pitäisi ensisijaisesti pystyä tekemään sivustolla?");if(c.pending==="size")return say(l,"Roughly how large should the site be: one landing page, a few separate pages, or a larger multi-page site?","Примерно какой объём нужен: одна страница, несколько отдельных страниц или большой многостраничный сайт?","Kuinka laaja sivuston pitäisi olla: yksi sivu, muutama sivu vai suurempi monisivuinen sivusto?");return"";}
function summary(c,l){const b=sanitizeBrief(c.websiteBrief),p=[];p.push(say(l,"Here is the brief as it stands 😊","Вот текущий бриф 😊","Tässä on briiffi tällä hetkellä 😊"));if(b.business)p.push(say(l,"Business: "+b.business+".","Бизнес: "+b.business+".","Yritys: "+b.business+"."));if(b.businessDescription)p.push(say(l,"Business description: "+b.businessDescription+".","Описание бизнеса: "+b.businessDescription+".","Yrityksen kuvaus: "+b.businessDescription+"."));if(b.goal)p.push(say(l,"Website goal: "+b.goal+".","Цель сайта: "+b.goal+".","Sivuston tavoite: "+b.goal+"."));if(b.size)p.push(say(l,"Website size: "+b.size+".","Размер сайта: "+b.size+".","Sivuston koko: "+b.size+"."));if(b.requirements.length)p.push(say(l,"Confirmed requirements: "+b.requirements.join(", ")+".","Подтверждённые требования: "+b.requirements.join(", ")+".","Vahvistetut vaatimukset: "+b.requirements.join(", ")+"."));if(b.recommendedStructure)p.push(say(l,"Suggested structure: "+b.recommendedStructure+".","Предлагаемая структура: "+b.recommendedStructure+".","Ehdotettu rakenne: "+b.recommendedStructure+"."));if(b.recommendedPackage)p.push(say(l,"Closest package: "+b.recommendedPackage+" "+((C.packages[b.recommendedPackage]||{}).price||"")+".","Ближайший пакет: "+b.recommendedPackage+" "+((C.packages[b.recommendedPackage]||{}).price||"")+".","Lähin paketti: "+b.recommendedPackage+" "+((C.packages[b.recommendedPackage]||{}).price||"")+"."));else if(b.needsAlexReview)p.push(say(l,"The exact package and price need Alex's review because of the requested functionality.","Точный пакет и цена требуют проверки Алекса из-за запрошенных функций.","Tarkka paketti ja hinta vaativat Alexin tarkistuksen toimintojen vuoksi."));p.push(say(l,"Nothing is sent automatically. You can change this brief, start a new one, or pass it to Alex later.","Ничего автоматически не отправляется. Вы можете изменить этот бриф, начать новый или позже передать его Алексу.","Mitään ei lähetetä automaattisesti. Voit muuttaa briiffiä, aloittaa uuden tai välittää sen Alexille myöhemmin."));return p.join(" ");}

function renderText(text,pose="neutral"){W.ui.mode(W.state.tour()?.active?"tour":"chat");W.ui.pose(pose);W.ui.bubbleText(text);}
function applyRoleResult(r,label){if(!r)return false;const c=W.state.context(),b=r.brief?sanitizeBrief(r.brief):sanitizeBrief(c.websiteBrief),m=sanitizeMemory(r.memory||c.clientMemory,b);W.state.patch({language:r.language||c.language,role:r.role||c.role,topic:r.topic!==undefined?r.topic:c.topic,pending:r.pending!==undefined?r.pending:c.pending,pendingAction:r.pendingAction!==undefined?r.pendingAction:c.pendingAction,websiteBrief:b,clientMemory:m,lastRoute:label||"V030_ROLE"});if(r.kind==="tour"){W.tour.start(r.language||c.language||"en");return true;}if(r.kind==="answer"){renderText(r.text,r.pose||"neutral");return true;}return false;}
function resetSideTurns(){const c=W.state.context();if(c.briefSideTurns)W.state.patch({briefSideTurns:0});}

function startNewBrief(l){const c=W.state.context(),mem=sanitizeMemory(c.clientMemory,freshBrief());mem.business=null;mem.businessRaw=null;mem.businessDescription=null;const b=freshBrief();W.state.patch({language:l,role:"secretary",topic:"website_consultation",pending:"business",pendingAction:null,websiteBrief:b,clientMemory:mem,briefSideTurns:0,humanTechCasualTurns:0,lastRoute:"V030_NEW_BRIEF"});renderText(say(l,"Absolutely 😊 Let's start fresh. Nothing from any earlier brief was sent automatically. What kind of business is this website for?","Конечно 😊 Начнём с чистого листа. Ни один предыдущий бриф автоматически никуда не отправлялся. Для какого бизнеса нужен этот сайт?","Totta kai 😊 Aloitetaan puhtaalta pöydältä. Mitään aiempaa briiffiä ei lähetetty automaattisesti. Millaiselle yritykselle sivusto tulee?"),"professional");}
function websiteEntry(l){const c=W.state.context();if(R.briefActive(c)){renderText(say(l,"We're already working on your website brief 😊 ","Мы уже работаем над вашим брифом сайта 😊 ","Työstämme jo verkkosivubriiffiäsi 😊 ")+pendingQuestion(c,l),"professional");return;}if(hasProject(c)){W.state.patch({pendingAction:"choose_website_context",lastRoute:"V030_WEBSITE_CONTEXT_CHOICE"});renderText(say(l,"Sure 😊 I remember "+projectLabel(c,l)+". Would you like to continue that project, or start a new website brief?","Конечно 😊 Я помню "+projectLabel(c,l)+". Хотите продолжить этот проект или начать новый бриф сайта?","Totta kai 😊 Muistan projektisi. Haluatko jatkaa sitä vai aloittaa uuden verkkosivubriiffin?"),"professional");return;}startNewBrief(l);}
function continueBrief(l){const c=W.state.context();if(!hasProject(c)){startNewBrief(l);return;}const p=nextPending(c);W.state.patch({role:"secretary",topic:"website_consultation",pending:p,pendingAction:null,lastRoute:"V030_CONTINUE_BRIEF"});if(p)renderText(say(l,"Of course 😊 Let's continue. ","Конечно 😊 Продолжим. ","Totta kai 😊 Jatketaan. ")+pendingQuestion(Object.assign({},c,{pending:p,pendingAction:null}),l),"professional");else renderText(say(l,"Of course 😊 I remember the completed brief. You can change something, add a requirement, ask me to show the brief, or start a new one.","Конечно 😊 Я помню готовый бриф. Можно что-то изменить, добавить требование, попросить показать бриф или начать новый.","Totta kai 😊 Muistan valmiin briiffin. Voit muuttaa sitä, lisätä vaatimuksen, pyytää briiffin näkyviin tai aloittaa uuden."),"professional");}

function humanSocial(intent,l){const c=W.state.context(),n=Number(c.humanTechCasualTurns||0)+1;W.state.patch({humanTechCasualTurns:n,lastRoute:"V030_HUMAN_TECH"});if(intent==="greeting"){renderText(say(l,"Hi 😊 Nice to see you. How are you?","Привет 😊 Рада вас видеть. Как ваши дела?","Hei 😊 Mukava nähdä sinua. Mitä kuuluu?"));return;}if(R.smalltalk(c.lastUser||"")){}const steer=n>=3?say(l," Since you're here on Alex Node, is there anything you'd like to know about websites, IT support, ANITA, services or prices?"," Раз уж вы на Alex Node, хотите узнать что-нибудь о сайтах, IT-поддержке, ANITA, услугах или ценах?"," Koska olet Alex Nodella, haluaisitko tietää jotain verkkosivuista, IT-tuesta, ANITAsta, palveluista tai hinnoista?"):say(l," No rush — when you're ready, tell me what brought you to Alex Node today."," Не спешите — когда будете готовы, расскажите, что привело вас сегодня в Alex Node."," Ei kiirettä — kun olet valmis, kerro mikä toi sinut tänään Alex Nodelle.");renderText(say(l,"I'm doing well, thanks for asking 😊 How about you?","У меня всё хорошо, спасибо, что спросили 😊 А у вас?","Minulla menee hyvin, kiitos kun kysyit 😊 Entä sinulla?")+steer);}
function metaAnswer(text,l){const x=R.norm(text);if(/\b(?:are you ai|are you an ai|your ai status|ai status)\b/i.test(x)||/ты.*ии|статус.*ии/i.test(x))return say(l,"Yes 😊 I'm ANITA, Alex Node's virtual IT Assistant. I use AI for extended assistance, together with structured Alex Node knowledge, rules and memory.","Да 😊 Я ANITA, виртуальный IT-ассистент Alex Node. Для расширенной помощи я использую ИИ вместе со структурированными знаниями Alex Node, правилами и памятью.","Kyllä 😊 Olen ANITA, Alex Noden virtuaalinen IT-assistentti. Käytän tekoälyä yhdessä Alex Noden rakenteisen tiedon, sääntöjen ja muistin kanssa.");if(/\b(?:who created you|who made you)\b/i.test(x)||/кто тебя (?:создал|сделал)/i.test(x))return say(l,"I was created by Alex Node 😊","Меня создал Alex Node 😊","Minut loi Alex Node 😊");if(/\b(?:what model are you|which model are you|what ai are you|your brain|how do you work)\b/i.test(x)||/какая.*модель|твой мозг|как ты работаешь/i.test(x))return say(l,"I can explain what I can do, but I don't disclose Alex Node's internal implementation, prompts, credentials or proprietary details 😊","Я могу рассказать, что умею, но не раскрываю внутреннюю реализацию Alex Node, промпты, данные доступа или закрытые технические детали 😊","Voin kertoa mitä osaan, mutta en paljasta Alex Noden sisäistä toteutusta, kehotteita, tunnuksia tai suljettuja teknisiä yksityiskohtia 😊");return say(l,"I'm ANITA — Alex Node's virtual IT Assistant 😊 My main specialty is IT assistance, and I also help with Alex Node services, websites and virtual-character projects.","Я ANITA — виртуальный IT-ассистент Alex Node 😊 Моя основная специализация — IT-помощь, а ещё я помогаю с услугами Alex Node, сайтами и проектами виртуальных персонажей.","Olen ANITA — Alex Noden virtuaalinen IT-assistentti 😊 Pääalueeni on IT-apu, ja autan myös Alex Noden palveluissa, verkkosivuissa ja virtuaalihahmoprojekteissa.");}

async function askAI(prompt,l){try{const a=await W.ai.ask(prompt,l);return a&&a.ok&&a.answer?clean(a.answer):null;}catch(_){return null;}}
async function domainAnswer(text,l){const r=W.roles.route(text);if(r&&r.kind==="tour"){await W.tour.start(r.language||l);return null;}if(r&&r.kind==="answer"){if(r.topic==="website_consultation"){applyRoleResult(r,"V030_PROJECT_ENTRY_ROLE");return null;}return r.text;}const a=await askAI("ALEX NODE ASSISTANT. Answer briefly in the visitor's language. Stay within Alex Node: websites, design, IT support, ANITA/virtual characters, services, packages, prices, business workflows and related questions. Do not invent prices, availability or promises. Visitor: "+JSON.stringify(String(text||"")),l);return a||say(l,"I can help with Alex Node services, websites, IT support, ANITA, packages and prices 😊 What would you like to know?","Я могу помочь с услугами Alex Node, сайтами, IT-поддержкой, ANITA, пакетами и ценами 😊 Что хотите узнать?","Voin auttaa Alex Noden palveluissa, verkkosivuissa, IT-tuessa, ANITAssa, paketeissa ja hinnoissa 😊 Mitä haluaisit tietää?");}
async function offTopicAnswer(text,l){const x=clean(text);const simple=x.match(/^\s*(-?\d+(?:\.\d+)?)\s*([+\-*\/])\s*(-?\d+(?:\.\d+)?)\s*\??\s*$/);if(simple){const a=Number(simple[1]),b=Number(simple[3]),op=simple[2];let v=op==="+"?a+b:op==="-"?a-b:op==="*"?a*b:(b===0?null:a/b);if(v!==null)return String(v);}return await askAI("SHORT SIDE QUESTION. Answer in no more than two short sentences in the visitor's language. Do not start a long general conversation. Visitor: "+JSON.stringify(String(text||"")),l);}

async function answerSideDuringBrief(text,intent,l){const c=W.state.context(),n=Number(c.briefSideTurns||0);if(n>=1){renderText(say(l,"I can answer more after we finish this brief 😊 Let's keep the project accurate first. ","Я отвечу на остальные вопросы после того, как мы закончим этот бриф 😊 Сначала сохраним проект точным. ","Voin vastata muihin kysymyksiin, kun olemme viimeistelleet briiffin 😊 Pidetään projekti ensin tarkkana. ")+pendingQuestion(c,l),"professional");return;}W.state.patch({briefSideTurns:n+1,lastRoute:"V030_SIDE_DURING_BRIEF"});let a=null;if(intent==="meta")a=metaAnswer(text,l);else if(intent==="project_side_question")a=await domainAnswer(text,l);else if(intent==="greeting"||intent==="social")a=intent==="greeting"?say(l,"Hi 😊","Привет 😊","Hei 😊"):say(l,"I'm doing well, thank you 😊","У меня всё хорошо, спасибо 😊","Minulla menee hyvin, kiitos 😊");else a=await offTopicAnswer(text,l);if(!a)a=say(l,"That's a separate question 😊","Это отдельный вопрос 😊","Se on erillinen kysymys 😊");renderText(a+" "+say(l,"Back to our brief:","Вернёмся к нашему брифу:","Palataan briiffiin:")+" "+pendingQuestion(W.state.context(),l),"professional");}

function handleConfirmNeed(text,l){const c=W.state.context(),pa=String(c.pendingAction||""),key=pa.slice("confirm_need:".length).trim().toLowerCase();if(!R.yes(text)&&!R.no(text)){renderText(say(l,"Just to keep the brief accurate, please answer yes or no 😊 ","Чтобы бриф был точным, ответьте, пожалуйста, да или нет 😊 ","Jotta briiffi pysyy tarkkana, vastaa kyllä tai ei 😊 ")+(W.semanticAdapter?.questionForNeed?W.semanticAdapter.questionForNeed(key,l,c.websiteBrief||{}):""),"professional");return;}const b=sanitizeBrief(c.websiteBrief),accepted=R.yes(text);if(accepted){const add=W.semanticAdapter?.requirementsFromNeed?W.semanticAdapter.requirementsFromNeed(key):[key];b.requirements=uniq([...b.requirements,...add]);b.rejectedSuggestions=b.rejectedSuggestions.filter(v=>v!==key);if(!b.goal&&W.semanticAdapter?.goalFromNeed)b.goal=W.semanticAdapter.goalFromNeed(key)||b.goal;}else b.rejectedSuggestions=uniq([...b.rejectedSuggestions,key]);b.inferredSuggestions=b.inferredSuggestions.filter(v=>v!==key&&!(accepted&&key==="availability calendar"&&v==="booking"));const cand=W.semanticAdapter?.nextCandidate?W.semanticAdapter.nextCandidate(b):null;let pending=null,pendingAction=null,textOut="";if(cand){pending=b.goal?(!b.size?"size":c.pending):"goal";pendingAction="confirm_need:"+cand;textOut=(accepted?say(l,"Great — I've added that as a confirmed requirement 😊 ","Отлично — я добавила это как подтверждённое требование 😊 ","Hyvä — lisäsin sen vahvistetuksi vaatimukseksi 😊 "):say(l,"Understood — I won't add that as a requirement 😊 ","Поняла — я не буду добавлять это в требования 😊 ","Selvä — en lisää sitä vaatimukseksi 😊 "))+W.semanticAdapter.questionForNeed(cand,l,b);}else{pending=!b.goal?"goal":!b.size?"size":null;textOut=(accepted?say(l,"Great — I've added that as a confirmed requirement 😊 ","Отлично — я добавила это как подтверждённое требование 😊 ","Hyvä — lisäsin sen vahvistetuksi vaatimukseksi 😊 "):say(l,"Understood — I won't add that as a requirement 😊 ","Поняла — я не буду добавлять это в требования 😊 ","Selvä — en lisää sitä vaatimukseksi 😊 "))+(pending?pendingQuestion(Object.assign({},c,{websiteBrief:b,pending,pendingAction:null}),l):say(l,"We can continue from the updated brief.","Можем продолжить с обновлённым брифом.","Voimme jatkaa päivitetystä briiffistä."));}W.state.patch({websiteBrief:b,pending,pendingAction,briefSideTurns:0,lastRoute:"V030_CONFIRM_NEED"});renderText(textOut,"professional");}

async function briefAnswer(text,l){const c=W.state.context();resetSideTurns();if(String(c.pendingAction||"").startsWith("confirm_need:")){handleConfirmNeed(text,l);return;}W.ui.pose("thinking");W.ui.bubbleText(say(l,"Hmm... let me think 😊","Хм... дай подумать 😊","Hmm... mietitään 😊"));try{if((c.pending==="business"||c.pending==="goal")&&W.semantic&&W.semanticAdapter){const sem=await W.semantic.interpret(text,l),handoff=W.semanticAdapter.buildHandoff(sem,text);if(handoff&&handoff.confidence>=0.60){const sr=W.semanticAdapter.routeToSecretary(handoff);if(sr&&sr.kind==="answer"){const b=sanitizeBrief(sr.brief||W.state.context().websiteBrief);if(c.pending==="business"&&b.business){const p=splitBusiness(b.business);b.business=p.business;if(p.description&&!b.businessDescription)b.businessDescription=p.description;}const m=sanitizeMemory(sr.memory||W.state.context().clientMemory,b);W.state.patch({language:sr.language||l,role:"secretary",topic:"website_consultation",pending:sr.pending!==undefined?sr.pending:W.state.context().pending,pendingAction:sr.pendingAction!==undefined?sr.pendingAction:W.state.context().pendingAction,websiteBrief:b,clientMemory:m,briefSideTurns:0,lastRoute:"V030_SEMANTIC_BRIEF"});renderText(sr.text,sr.pose||"professional");return;}}}const r=W.roles.route(text);if(r&&r.kind==="answer"){applyRoleResult(r,"V030_DETERMINISTIC_BRIEF");resetSideTurns();return;}renderText(say(l,"I want to keep the brief accurate 😊 ","Я хочу сохранить бриф точным 😊 ","Haluan pitää briiffin tarkkana 😊 ")+pendingQuestion(W.state.context(),l),"professional");}catch(_){renderText(say(l,"I want to keep the brief accurate 😊 ","Я хочу сохранить бриф точным 😊 ","Haluan pitää briiffin tarkkana 😊 ")+pendingQuestion(W.state.context(),l),"professional");}}

async function prepareBrief(l){const c=W.state.context();if(!hasProject(c)){renderText(say(l,"We haven't started a website brief yet 😊 If you want, we can start one now.","Мы ещё не начинали бриф сайта 😊 Если хотите, можем начать прямо сейчас.","Emme ole vielä aloittaneet verkkosivubriiffiä 😊 Voimme aloittaa sen nyt, jos haluat."),"professional");return;}const p=nextPending(c);if(p){W.state.patch({topic:"website_consultation",pending:p,pendingAction:null});renderText(say(l,"Let's finish the brief first so it is useful 😊 ","Давайте сначала закончим бриф, чтобы он был полезным 😊 ","Viimeistellään briiffi ensin, jotta siitä on hyötyä 😊 ")+pendingQuestion(Object.assign({},c,{pending:p,pendingAction:null}),l),"professional");return;}renderText(summary(c,l),"professional");}

async function handle(text){const route=R.classify(text),l=route.language,c=W.state.context();W.state.patch({language:l,lastUser:text,lastIntent030:route.intent});
  if(R.briefActive(c)&&["greeting","social","meta","project_side_question","side_question","offtopic_question"].includes(route.intent)){await answerSideDuringBrief(text,route.intent,l);return;}
  switch(route.intent){
    case"new_brief":startNewBrief(l);return;
    case"website_entry":websiteEntry(l);return;
    case"continue_brief":continueBrief(l);return;
    case"choose_website_context_unclear":renderText(say(l,"Do you want to continue the website project I remember, or start a new brief? 😊","Хотите продолжить проект сайта, который я помню, или начать новый бриф? 😊","Haluatko jatkaa muistamaani projektia vai aloittaa uuden briiffin? 😊"),"professional");return;
    case"prepare_brief":await prepareBrief(l);return;
    case"greeting":case"social":humanSocial(route.intent,l);return;
    case"meta":renderText(metaAnswer(text,l));return;
    case"brief_answer":await briefAnswer(text,l);return;
    case"unclear_during_brief":renderText(say(l,"Just so I don't save anything incorrectly: is that part of the website brief, or a separate comment? 😊 ","Чтобы я ничего не записала неправильно: это часть брифа сайта или отдельный комментарий? 😊 ","Jotta en tallenna mitään väärin: kuuluuko tuo verkkosivubriiffiin vai onko se erillinen kommentti? 😊 ")+pendingQuestion(c,l),"professional");return;
    case"project_question":{const a=await domainAnswer(text,l);if(a)renderText(a,"neutral");return;}
    case"offtopic_question":{const n=Number(c.offtopicTurns030||0);if(n>=2){renderText(say(l,"I can chat a little 😊 but here I'm mainly here for Alex Node, websites, IT support, ANITA, services and related business questions. What would you like to know about that?","Немного поболтать можно 😊 но здесь я в первую очередь помогаю с Alex Node, сайтами, IT-поддержкой, ANITA, услугами и связанными бизнес-вопросами. Что из этого вас интересует?","Voimme jutella vähän 😊 mutta täällä autan ensisijaisesti Alex Nodeen, verkkosivuihin, IT-tukeen, ANITAan, palveluihin ja niihin liittyviin yrityskysymyksiin. Mistä haluaisit tietää?"));return;}const a=await offTopicAnswer(text,l);W.state.patch({offtopicTurns030:n+1});renderText((a||say(l,"I can answer that briefly 😊","Я могу коротко ответить на это 😊","Voin vastata siihen lyhyesti 😊"))+say(l," If you'd like, I can also help with anything around Alex Node."," Если хотите, я также могу помочь с любыми вопросами об Alex Node."," Halutessasi voin auttaa myös Alex Nodeen liittyvissä asioissa."));return;}
    default:{const a=await offTopicAnswer(text,l);renderText((a||say(l,"I'm listening 😊","Я слушаю 😊","Kuuntelen 😊"))+say(l," What brought you to Alex Node today?"," Что привело вас сегодня в Alex Node?"," Mikä toi sinut tänään Alex Nodelle?"));return;}
  }
}

async function process(){if(busy||!queue.length)return;busy=true;try{await handle(queue.shift());}finally{busy=false;process();}}
function enqueue(){const el=q(),v=el&&el.value.trim();if(!v)return;if(el)el.value="";queue.push(v);process();}
let bound=false;function bind(){if(bound)return;bound=true;document.addEventListener("click",e=>{const b=e.target&&e.target.closest?e.target.closest("#an50-send"):null;if(!b)return;e.preventDefault();enqueue();});document.addEventListener("keydown",e=>{const i=e.target&&e.target.closest?e.target.closest("#an50-input"):null;if(!i||e.key!=="Enter")return;e.preventDefault();enqueue();});}
function boot(){sanitizeStored();bind();const t=W.state.tour();if(t&&t.active&&!home()){W.ui.mode("tour");W.tour.resume();return;}if(home()){W.state.clearTour();W.ui.hello();let stage="hello";const root=W.ui.root();if(root)root.onclick=e=>{if(e.target.closest("#an50-chat,.an50-tour-controls,.an50-btn"))return;if(stage==="hello"){stage="guide";W.ui.guideIntro();return;}if(stage==="guide"){stage="tour";W.tour.start(W.state.context().language||"en");}};}else W.ui.ready();window.__ANITA_V030__={singleRouter:true,humanTech:true,briefMemoryBoundary:true,newBriefAnytime:true,sideQuestionResume:true};console.log("[ANITA 0.3.0 HUMAN-TECH CORE]",window.__ANITA_V030__);}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();