(function(root){"use strict";const A=root.ANITA51=root.ANITA51||{};const opt=(v,en,ru,fi)=>({value:v,labels:{en,ru,fi}});
const Q={
business:{id:"business",field:"business",type:"free",prompt:{en:"Tell me a little about your business or project — what do you do?",ru:"Расскажите немного о вашем бизнесе или проекте — чем вы занимаетесь?",fi:"Kerro hieman yrityksestäsi tai projektistasi — mitä teet?"}},
goal:{id:"goal",field:"goal",type:"free",prompt:{en:"What should visitors be able to do on the website? For example, they might browse your work, buy something, contact you, leave feedback, book a service — or do several of these.",ru:"Что посетители должны иметь возможность делать на сайте? Например: смотреть ваши работы, покупать, связываться с вами, оставлять отзывы, записываться — или делать сразу несколько вещей.",fi:"Mitä kävijöiden pitäisi voida tehdä sivustolla? Esimerkiksi tutustua töihisi, ostaa, ottaa yhteyttä, antaa palautetta, varata palvelu — tai tehdä useita näistä."}},
size:{id:"size",field:"size",type:"choice_or_count",prompt:{en:"Roughly how large should the site be?",ru:"Какого примерно размера нужен сайт?",fi:"Minkä kokoinen sivuston pitäisi olla?"},options:[opt("one page","One page","Одна страница","Yksi sivu"),opt("two pages","Two pages","Две страницы","Kaksi sivua"),opt("a few pages","A few pages","Несколько страниц","Muutama sivu"),opt("four plus pages","4+ pages","4+ страницы","4+ sivua"),opt("clarify_size","What’s the difference?","В чём разница?","Mitä eroa?")]},
requirements:{id:"requirements",field:"requirements",type:"free",prompt:{en:"Is there anything else the website definitely needs? You can list as many things as you want — or say nothing special.",ru:"Есть ли ещё что-то, что сайту точно нужно? Можете перечислить сколько угодно пунктов — или сказать «ничего особенного».",fi:"Tarvitseeko sivusto varmasti vielä jotain muuta? Voit luetella niin monta asiaa kuin haluat — tai sanoa ettei mitään erityistä."}},
confirm:{id:"confirm",type:"confirm",prompt:{en:"Does this brief look correct?",ru:"Всё в брифе правильно?",fi:"Onko brief oikein?"},options:[opt("yes","Yes, correct ✓","Да, всё верно ✓","Kyllä, oikein ✓"),opt("change","Change something","Изменить","Muuta jotain"),opt("prices","Ask about prices","Спросить о ценах","Kysy hinnoista")]},
edit:{id:"edit",type:"free",prompt:{en:"Of course. What would you like to change?",ru:"Конечно. Что хотите изменить?",fi:"Totta kai. Mitä haluat muuttaa?"}},
handoff:{id:"handoff",type:"action",prompt:{en:"Would you like me to pass this brief to Alex?",ru:"Передать этот бриф Alex?",fi:"Haluatko, että välitän briefin Alexille?"},options:[opt("send","Send to Alex","Передать Alex","Lähetä Alexille"),opt("change","Change brief","Изменить бриф","Muuta briefiä"),opt("later","Not now","Не сейчас","Ei nyt")]}
};A.Questions={get:id=>Q[id]||null,all:Q,prompt(q,l){return q&&q.prompt?(q.prompt[l]||q.prompt.en):""}};})(window);