(function(root){"use strict";const A=root.ANITA51=root.ANITA51||{};
const opt=(v,en,ru,fi)=>({value:v,labels:{en,ru,fi}});
const Q={
business:{id:"business",field:"business",type:"free",prompt:{en:"Tell me a little about your business or project — what do you do?",ru:"Расскажите немного о вашем бизнесе или проекте — чем вы занимаетесь?",fi:"Kerro hieman yrityksestäsi tai projektistasi — mitä teet?"}},
goal:{id:"goal",field:"goal",type:"free",prompt:{en:"What should visitors be able to do on the website?",ru:"Что посетители должны иметь возможность делать на сайте?",fi:"Mitä kävijöiden pitäisi voida tehdä sivustolla?"},options:[opt("contact","Contact you","Связаться с вами","Ottaa yhteyttä"),opt("buy","Buy something","Купить","Ostaa"),opt("book","Book a service","Записаться","Varata palvelu"),opt("learn","Learn about the business","Узнать о бизнесе","Tutustua yritykseen")]},
size:{id:"size",field:"size",type:"choice_or_count",prompt:{en:"Roughly what size of site are you thinking of?",ru:"Какого примерно размера сайт вы представляете?",fi:"Minkä kokoista sivustoa ajattelet?"},options:[opt("one page","One page","Одна страница","Yksi sivu"),opt("a few pages","A few pages","Несколько страниц","Muutama sivu"),opt("larger multi-page","Larger multi-page","Большой многостраничный","Laaja monisivuinen"),opt("clarify_size","What’s the difference?","В чём разница?","Mitä eroa?")]},
requirements:{id:"requirements",field:"requirements",type:"multi_or_free",prompt:{en:"Anything specific you already know you need? You can choose options or describe it in your own words.",ru:"Есть ли что-то конкретное, что уже точно нужно? Можно выбрать варианты или написать своими словами.",fi:"Onko jotain erityistä, mitä jo tiedät tarvitsevasi? Voit valita tai kirjoittaa omin sanoin."},options:[opt("online store","Online store","Интернет-магазин","Verkkokauppa"),opt("booking","Booking","Онлайн-запись","Ajanvaraus"),opt("contact form","Contact form","Форма связи","Yhteydenottolomake"),opt("multiple languages","Multiple languages","Несколько языков","Useita kieliä"),opt("none","Nothing special","Ничего особенного","Ei mitään erityistä")]},
confirm:{id:"confirm",type:"confirm",prompt:{en:"Does this brief look correct?",ru:"Всё в брифе правильно?",fi:"Onko brief oikein?"},options:[opt("yes","Yes, correct ✓","Да, всё верно ✓","Kyllä, oikein ✓"),opt("change","Change something","Изменить","Muuta jotain"),opt("prices","Ask about prices","Спросить о ценах","Kysy hinnoista")]},
edit:{id:"edit",type:"free",prompt:{en:"Of course. What would you like to change?",ru:"Конечно. Что хотите изменить?",fi:"Totta kai. Mitä haluat muuttaa?"}},
handoff:{id:"handoff",type:"action",prompt:{en:"Would you like me to pass this brief to Alex?",ru:"Передать этот бриф Alex?",fi:"Haluatko, että välitän briefin Alexille?"},options:[opt("send","Send to Alex","Передать Alex","Lähetä Alexille"),opt("change","Change brief","Изменить бриф","Muuta briefiä"),opt("later","Not now","Не сейчас","Ei nyt")]}
};
A.Questions={get:id=>Q[id]||null,all:Q,prompt(q,l){return q&&q.prompt?(q.prompt[l]||q.prompt.en):""}};
})(window);