(function(root){"use strict";const A=root.ANITA51=root.ANITA51||{};let bound=false,busy=false;
function bubble(){return document.getElementById("an50-bubble")}function input(){return document.getElementById("an50-input")}
function style(){if(document.getElementById("anita51-style"))return;const s=document.createElement("style");s.id="anita51-style";s.textContent=".anita51-choices{display:flex;flex-wrap:wrap;gap:7px;margin-top:10px}.anita51-choices button{border:1px solid #bbb;border-radius:18px;background:#fff;padding:7px 11px;cursor:pointer;font-size:13px}.anita51-choices button.primary{font-weight:700}";document.head.appendChild(s)}
function show(t){const b=bubble();if(!b)return;b.textContent=String(t||"");b.classList.add("show")}
function buttons(q,l){const b=bubble();if(!b||!q||!q.options)return;style();const box=document.createElement("div");box.className="anita51-choices";q.options.forEach(o=>{const bt=document.createElement("button");bt.type="button";bt.textContent=(o.labels&&(o.labels[l]||o.labels.en))||o.value;if(o.value==="yes"||o.value==="send")bt.className="primary";bt.onclick=e=>{e.preventDefault();submit(o.value)};box.appendChild(bt)});b.appendChild(box)}
function render(r){if(!r)return;show(r.text||"");if(r.showButtons&&r.pending)setTimeout(()=>buttons(r.pending,r.language||A.State.get().language||"en"),10)}
async function submit(forced){if(busy)return;const i=input(),text=forced||String(i&&i.value||"").trim();if(!text)return;if(i&&!forced)i.value="";busy=true;show("ANITA is thinking…");try{render(await A.Interpreter.handle(text))}catch(e){console.error("[ANITA 51 UI]",e);show("ANITA 51 test error: "+(e.message||e))}finally{busy=false}}
function inactivity(){setInterval(function(){const s=A.State.get(),m=s.brief&&s.brief.meta;if(!m||m.status!=="draft")return;const now=Date.now(),last=m.lastActivityAt||m.createdAt||now;if(!m.inactivityPromptAt&&now-last>=600000){m.inactivityPromptAt=now;m.expiresAt=now+1200000;A.State.update({brief:s.brief,phase:"inactivity_check"});const q={id:"inactivity",type:"action",options:[{value:"continue",labels:{en:"Continue brief",ru:"Продолжить бриф",fi:"Jatka briefiä"}},{value:"cancel",labels:{en:"Cancel brief",ru:"Отменить бриф",fi:"Peru brief"}}]};A.State.setPending(q);render({text:s.language==="ru"?"Похоже, вы отвлеклись 😊 Хотите продолжить заполнение заявки или отменить её?":"Looks like you may have stepped away 😊 Would you like to continue the request or cancel it?",pending:q,showButtons:true,language:s.language});return}if(m.inactivityPromptAt&&m.expiresAt&&now>=m.expiresAt){A.State.cancelBrief("inactivity");render({text:s.language==="ru"?"Похоже, вы надолго отвлеклись, поэтому я отменила незавершённый бриф, чтобы не держать лишние данные. Если захотите вернуться — начнём заново 😊":"It looks like you were away for a while, so I cancelled the unfinished brief rather than keep an inactive request. If you come back to it, we can simply start again 😊",showButtons:false,language:s.language})}},15000)}
function bind(){if(bound)return;const i=input(),bt=document.getElementById("an50-send");if(!i||!bt){setTimeout(bind,100);return}bound=true;inactivity();bt.addEventListener("click",()=>submit());i.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();submit()}});console.log("[ANITA 51] UI bound with choices")}
A.UIBind={bind,render,submit};})(window);